### ISSUE TITLE
Something wrong with sit animation

### ISSUE THREAD

**Issue by Dragese** [ESX-Org/esx_sit#11]
![sit](https://user-images.githubusercontent.com/42306225/45264193-13f5e480-b452-11e8-8d8b-cc7b3e6378c6.png)
Why i am sitting like this?

**Comment by Betonejro** [comment]
add 

`FreezeEntityPosition(playerPed, true)`

in function sit close by `FreezeEntityPosition(object, true)`

**Comment by renaiku** [comment]
Or correct the offset for this props ...

**Comment by nearbyplayer** [comment]
Submit a PR, until then this is closed.
