### ISSUE TITLE
Cannot stand

### ISSUE THREAD

**Issue by zabattaro** [ESX-Org/esx_sit#14]
I try to fix it, but i cannot make it work. When you press shift+ e again while u are sitting, make animation, but it goes back to the chair. For what i see, the Local sitting is not changing boolean. cuz if i add 

If sitting == true then
    wakeup()

it not work. and i if add wakeup(playerped) , it dont work too.

**Comment by FRANkiller13** [comment]
@zabattaro https://github.com/ESX-Org/esx_sit/pull/9

**Comment by nearbyplayer** [comment]
Fixed in #9
