### ISSUE TITLE
does it work with onesync ?

### ISSUE THREAD

**Issue by RomaRosso** [ESX-Org/esx_sit#16]
this is not working for me, i have 250 resources and i edited and have all of them configured properly , i cant find a way to enable players to sit with an animation (they can even sit in floor but not in chairs since i cant get one that loops and get in the right position for a good RP) So this is a very good option but instead of sit while i press shift + e the character will stand for a second in the chair or whatever that is listed in the file and go back to the original position, wont never sit or something. Any clue ?

**Comment by V3rSuS** [comment]
+1
