### ISSUE TITLE
Animation isn't synchronized

### ISSUE THREAD

**Issue by MJRamon** [ESX-Org/esx_sit#2]
Sitting animation (or player position, if to be exact) isn't synchronized with other players. For you your character is sitting at right heiht and direction, but for other players you sit above and your view point is off.

**Comment by MJRamon** [comment]
Are you guys on it? Thank you.

**Comment by renaiku** [comment]
No, not yet.

**Comment by MJRamon** [comment]
@renaiku 
Try
` TASK_START_SCENARIO_AT_POSITION(Ped ped, char *scenarioName, float x, float y, float z, float heading, int duration, BOOL sittingScenario, BOOL teleport)`
instead of SetEntityCoords, SetEntityHeading, FreezeEntityPosition, TaskStartScenarioInPlace
