### ISSUE TITLE
cant sit

### ISSUE THREAD

**Issue by a7mdobob** [ESX-Org/esx_sit#23]
![reref](https://user-images.githubusercontent.com/53619512/69775302-66cbd100-11a9-11ea-8345-2d659fc7b3af.png)

**Comment by duckhunter392** [comment]
@a7mdobob Fun fact: to help diagnose the issue it would really help to know what line of the code is throwing the error.

By placing your cursor over the line number, it makes it pretty difficult to tell what line in the code is causing the error. Just sayin'

**Comment by duckhunter392** [comment]
Fixed in #24
