### ISSUE TITLE
Can't stand

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/esx_sit#5]
Once you start sitting you can't stand back up. If you press Shift+E you stand up then sit back down again.

**Comment by CanGamers** [comment]
same thing here

**Comment by DevMinkh** [comment]
insert local playerPed = GetPlayerPed(-1) in function wakeup to set playerPed right. Then you'll be able to standup

**Comment by 1stLT** [comment]
It doesn't work for me either, I can't stand up.

**Comment by Bobblemend15** [comment]
You Press Shift + X you will stand back up

**Comment by WayCraft** [comment]
> insert local playerPed = GetPlayerPed(-1) in function wakeup to set playerPed right. Then you'll be able to standup

Thank you, this really works.

Correction
`function wakeup()
	local playerPed = GetPlayerPed(-1)
	ClearPedTasks(playerPed)
	sitting = false
	SetEntityCoords(playerPed, lastPos)
	FreezeEntityPosition(playerPed, false)
	FreezeEntityPosition(currentSitObj, false)
	TriggerServerEvent('esx_interact:leavePlace', currentSitObj)
	currentSitObj = nil
	currentScenario = nil
end`

**Comment by nearbyplayer** [comment]
Fixed in #9
